### PR TITLE
Improve toString of count constraints.

### PR DESCRIPTION
**Pull request by zherebjatjew**
1. Fixed bug which caused duplicate output of last var (cardinality) if where are less than 3 items in decvars.
2. Added separate output of cardinality and restricted value.

### CODE REVIEW

**Comment by cprudhom** [comment]
@zherebjatjew can I add your name in the CONTRIBUTORS file (with the agreement of your employer too) ?

**Comment by zherebjatjew** [comment]
It would be a pleasure for me. I'm just not sure what king of agreement you're talking about. My employer won't object me to be mentioned in contributor list, but I'm not sure whether he's willing to provide any official approvals.

**Comment by cprudhom** [comment]
Well I'm clearly not an expert in CLA, but I believe if he's aware that you contributed to open-source project, we're ok.

**Comment by zherebjatjew** [comment]
Yes, he is aware.

**Comment by cprudhom** [comment]
Ok. Could you give me your first name, last name and an email, or directly update the CONTRIBUTORS file ?

**Comment by zherebjatjew** [comment]
Dmitrij Zherebyatev
zherebjatjew@gmail.com

**Pull request merged**
